[package]
name = "temp_vrf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k256 = { version = "0.13.1", features = ["serde"] }
hex = "0.4.3"
rand_core = "0.6.4"
vrf = "0.2.4"
